- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanAdapter.kt
- opentelemetry-kotlin-api-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/NoopSpan.kt
- opentelemetry-kotlin-api/api/android/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/api/jvm/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/Span.kt
Alters the API for ending a span by creating function overloads, instead of a parameter with default values.
> Alter api for ending span

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/io/embrace/otel/KotlinConfig.kt
Sets an explicit API/Language version for Kotlin. We were doing this for `JavaCompile` but not in the Kotlin compiler options.
> Set the api/language version for kotlin

- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TracerAdapter.kt
- opentelemetry-kotlin-api-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/NoopTracer.kt
- opentelemetry-kotlin-api/api/android/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/api/jvm/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/Span.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanRelationships.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/Tracer.kt
Renames `SpanRelationshipContainer` to `SpanRelationships`.
> Rename span relationships

- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/context/ContextAdapter.kt
- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/context/ContextKeyRepository.kt
- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/logging/LoggerAdapter.kt
- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/logging/LoggerProviderAdapter.kt
- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TracerProviderAdapter.kt
- compat-kotlin-to-official/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/OpenTelemetrySdkTest.kt
- compat-kotlin-to-official/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/context/ContextAdapterTest.kt
- compat-kotlin-to-official/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/context/ContextKeyAdapterTest.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/Context.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/ContextImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/ContextKeyImpl.kt
Makes a few changes to the implementation of `Context` to avoid instantiating different keys when the underlying OTel Java implementation would use the same key. I've taken similar steps to avoid creating additional instances of the logger/tracer wrappers.
> Enhance implementation of Context

- compat-kotlin-to-official/api/jvm/compat-kotlin-to-official.api
- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanAdapter.kt
- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TracerAdapter.kt
- compat-kotlin-to-official/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExportTest.kt
- opentelemetry-kotlin-api-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/NoopSpan.kt
- opentelemetry-kotlin-api/api/android/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/api/jvm/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/Span.kt
Add accessors for SpanKind and startTimestamp, which are missing from the API.
> Add accessors for SpanKind and startTimestamp

- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TracerAdapter.kt
Calling  `setNoParent` on the builder is necessary so the Java SDK doesn't use the current span but instead uses the root as the parent context, thus not setting a parent span for the newly created span
> Call setNoParent on wrapped span builder if there's no parent

- buildSrc/src/main/kotlin/io/embrace/otel/KotlinConfig.kt
- gradle/libs.versions.toml
Updates the Kotlin version that is declared as a dependency in the POM file. By default the Kotlin Multiplatform Gradle Plugin  just uses whatever version of Kotlin we compile against, which is 2.1. We should target an older version of Kotlin instead for backwards compatibility, as otherwise consumers of this library will be forced to the latest version.
Checked POM file before and after this change.
> Update kotlin version used

- compat-kotlin-to-official/api/jvm/compat-kotlin-to-official.api
- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceExt.kt
- compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/OpenTelemetrySdk.kt
- examples/example-shared/src/main/java/io/embrace/opentelemetry/example/kotlin/OtelKotlinExample.kt
- opentelemetry-kotlin-api-noop/api/android/opentelemetry-kotlin-api-noop.api
- opentelemetry-kotlin-api-noop/api/jvm/opentelemetry-kotlin-api-noop.api
- opentelemetry-kotlin-api-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/NoopOpenTelemetry.kt
- opentelemetry-kotlin-api-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceExt.kt
- opentelemetry-kotlin-api/api/android/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/api/jvm/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstance.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceExt.kt
- opentelemetry-kotlin-testing/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/testing/junit4/OpenTelemetryRule.kt
- opentelemetry-kotlin-testing/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/testing/junit5/OpenTelemetryExtension.kt
Adds an entrypoint that can be used to access an entrypoint of OpenTelemetry instances. The syntax currently looks as follows:
```
OpenTelemetryInstance.noop()
OpenTelemetryInstance.default()
OpenTelemetryInstance.compatWithOtelJava(OpenTelemetryBuilder.build())
```
I'm open to different symbol names for both `OpenTelemetryInstance` and the functions themselves. In future I think we might want a DSL as part of `default()`, but we can see how this goes for now.
> Add entrypoint for accessing OpenTelemetry instances

- opentelemetry-kotlin-api/api/android/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/api/jvm/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/ExportResult.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordData.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordExporter.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanData.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanExporter.kt
Starts fleshing out the exporter API for spans and logs. `LogRecordData` and `SpanData` are left as placeholder types for now.
> Begin creating exporters api

- opentelemetry-kotlin-api/api/android/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/api/jvm/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/ExportResult.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/export/OperationResultCode.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/export/TelemetryCloseable.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordExporter.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordProcessor.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanExporter.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanProcessor.kt
Adds the initial interface that will be used for the `LogRecordProcessor` and `SpanProcessor` APIs.
> Add processor api

- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/bridge/OtelJavaLogRecordDataImpl.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/bridge/OtelJavaSpanDataImpl.kt
Adds classes for `SpanData` and `LogRecordData` that can be instantiated as we can't access the real implementations in opentelemetry-java directly, but we need to construct new objects for compatibility purposes.
> Add delegates for OTel java

- opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/ReadWriteLogRecord.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/ReadableLogRecord.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/bridge/InstrumentationScopeInfoExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/bridge/OtelJavaAttributesExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/export/ReadableLogRecordExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/ReadableSpanExt.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeReadableLogRecord.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeSpanContext.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/export/LogRecordExporterAdapterTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/SpanExporterAdapterTest.kt
Builds on #140 by creating mapping functions that allow the span/log exporters to work with backwards compatibility.
Added unit test coverage.
> Create mapping functions for span/log exporters

- opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadableSpan.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/export/ReadableLogRecordExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/ReadableSpanExt.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeReadableSpan.kt
Adds an `endTimestamp` property to the Span API.
> Add an endTimestamp property on Span API

- opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanProcessor.kt
- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/bridge/OtelJavaContextExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/export/OtelJavaLogRecordExporterAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/export/OtelJavaLogRecordProcessorAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/export/ReadableLogRecordExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/OtelJavaSpanExporterAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/OtelJavaSpanProcessorAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/ReadableSpanExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/init/LoggerProviderConfigImpl.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/init/TracerProviderConfigImpl.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/export/OtelJavaLogRecordExporterAdapterTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/OtelJavaSpanExporterAdapterTest.kt
Continues with code that hooks up the span/log processor added via the Kotlin API to an otel-java builder. The implementation of the decorating processor will follow in a subsequent PR.
> Continue hooking up span/log processors

- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/bridge/ResourceAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaSpanAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaStatusCodeConversion.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/OtelJavaSpanProcessorAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/ReadWriteSpanAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/ReadableLinkAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/ReadableSpanAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/ReadableSpanEventAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/ReadableSpanExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/AttributeContainerImpl.kt
Implements code that wraps Kotlin/Java OTel model classes so that the span processor can function. The functionality will be covered by an integration test that will test the whole system once everything is hooked up.
> Implement span processor mapping

- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceK2J.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/export/ReadWriteLogRecordAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/OpenTelemetrySdk.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/init/TracerProviderConfigImpl.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TracerProviderAdapter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/OpenTelemetrySdkTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/framework/InMemoryLogRecordExporter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/framework/InMemoryLogRecordProcessor.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/framework/InMemorySpanExporter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/framework/InMemorySpanProcessor.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/framework/OtelKotlinHarness.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/logging/LogExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_attrs.json
Updates the span/log export tests so they pass when using an OpenTelemetry Java instance configured via the Kotlin API.
> Update export tests to pass

- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TracerProviderAdapter.kt
Propagates schemaUrl to the `TracerProvider` implementation.
> Propagate schemaUrl to tracer provider

- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaSpanKindConversion.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanContextOtelJavaConverter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/StatusCodeConversion.kt
Makes a symbol public in the compat module. This will allow for the deletion of ~3 duplicate classes in embrace-android-sdk.
> Make symbol public

- opentelemetry-kotlin-api-ext/api/opentelemetry-kotlin-api-ext.api
- opentelemetry-kotlin-api-ext/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryExt.kt
- opentelemetry-kotlin-testing/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/testing/junit4/OpenTelemetryRule.kt
- opentelemetry-kotlin-testing/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/testing/junit5/OpenTelemetryExtension.kt
The OTel Java API have a helper to get a tracer with just the instrumentation scope name. Add something similar in an extension to the Kotlin OTel instance.
> Add simplified helper to get tracer and logger from OTel instance

- opentelemetry-java-typealiases/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/aliases/Aliases.kt
- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceJ2K.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/OtelJavaOpenTelemetrySdk.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/OtelJavaLogRecordBuilderAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/OtelJavaLoggerAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/OtelJavaLoggerBuilderAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/logging/OtelJavaLoggerProviderAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaSpanAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaSpanBuilderAdapter.kt
Implements code that allows the Kotlin implementation to be used via invocations of the Java API. A future PR will setup span/log exporting test cases for test coverage.
> Implement java to kotlin adapters

- opentelemetry-kotlin-api-ext/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanExt.kt
- opentelemetry-kotlin-api-ext/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanExtTest.kt
Fixes `recordException()` so that custom attributes are added.
Improved test coverage.
> Record exception fix

- opentelemetry-kotlin-testing/build.gradle.kts
- opentelemetry-kotlin-testing/gradle.properties
Ensures the opentelemetry-kotlin-testing module is published to allow backwards compatibility with tests using the Java API.
> Publish opentelemetry-kotlin-testing module

- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaSpanAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/context/ContextAdapter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/context/ContextRetrievalTest.kt
`OtelJavaSpanAdapter` should implement `ImplicitContextKeyed` as this allows for the underlying `OtelJavaSpan` instance to store itself in the context. Additionally, this adds some test coverage to ensure that context storage + retrieval works correctly.
> Make OtelJavaSpanAdapter implement ImplicitContextKeyed

- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TracerAdapter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExportTest.kt
Casting spanContext as SpanContextAdapter might fail, particularly in the case where an invalid span context created with SpanContext.invalid() is passed to create(). 
This PR addresses this issue, and adds a test for it. 
Creating a span passing an invalid parent results in a valid span.
> Address cast failure in TracerAdapter.findContext

- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/framework/serialization/SerializableSpanData.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/framework/serialization/conversion/SerializableSpanData.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_attrs.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_links.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_minimal.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_props.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_schema_url.json
Add instrumentationScopeInfo field to SerializableSpanData and update golden files to include tracer name, version, schema URL, and attributes.
> Update span serialization to include instrumentation scope info

- opentelemetry-kotlin-noop/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/NoopTests.kt
Add tests for opentelemetry-kotlin-noop, primarily for tracing: list attributes (strings, booleans, longs, doubles), span links with attributes, span operations, etc.
Also added a test that runs a logger, though it's a noop so it does nothing.
> Add tests for opentelemetry-kotlin-noop

- examples/telescope-app/app/src/main/java/io/embrace/opentelemetry/kotlin/telescope/telemetry/AppTracerProvider.kt
- examples/telescope-app/app/src/main/java/io/embrace/opentelemetry/kotlin/telescope/telemetry/SessionTelemetry.kt
- examples/telescope-app/gradle/libs.versions.toml
App wasn't compiling, so I'm using OpenTelemetryInstance.compatWithOtelJava(javaSdk) to init the Kotlin API, and updated the span package.
> Update telescope-app to use new API

- opentelemetry-kotlin-api-ext/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/FakeSpan.kt
- opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/Context.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadableSpan.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/Span.kt
- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/ReadableSpanExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/context/ContextExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TracerAdapter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/assertions/SpanContextAssertions.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/context/ContextRetrievalTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeReadableSpan.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/export/OtelJavaSpanExporterAdapterTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExportTest.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/ReadableSpanImpl.kt
- opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/NoopSpan.kt
- opentelemetry-kotlin-noop/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/NoopTests.kt
Tweaks the implementation of span context so that the span property isn't nullable. Additionally I've added a couple of functions that bind the OTel Java API.
> Tweak span context implementation

- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/bridge/context/OtelJavaContextAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/opentelemetry/api/trace/OtelJavaHooks.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExtTest.kt
Adds the ability to store spans in the Context, using the same key that opentelemetry-java uses.
> Implement storage of spans

- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/Context.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/context/ContextAdapter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/context/ContextRetrievalTest.kt
Removes operator overloading from the `Context` functions. The operator overloading allows context to be accessed with this syntax:
```
val ctx = ContextImpl()
val key = ctx.createKey<String>("test_key")
ctx[key] = ""
ctx[key]
```
However, I believe this syntax is unhelpful given context is immutable and always returns a new object. The correct usage of the API should look like this and the operator overloading nudges users of the API in the wrong direction via IDE auto-complete:
```
val key = ctx.createKey<String>("test_key")
val newCtx = ctx.set(key, "")
newCtx.get(key)
```
> Remove operator overloading from context

- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/context/ContextAdapterTest.kt
- opentelemetry-kotlin-implementation/api/opentelemetry-kotlin-implementation.api
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/ContextImpl.kt
Don't allow `ContextImpl` to be created explicitly, but make users go through an existing `Context` object's factory methods
> Make ContextImpl internal

- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaTracerBuilderAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaTracerProviderAdapter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaSpanExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_tracer_builder.json
• Implement `OtelJavaTracerBuilderAdapter`.
• Add `tracerBuilder()` method to `OtelJavaTracerProviderAdapter` for Java API compatibility  
• Enable passing custom `schemaUrl` and `instrumentationScopeVersion` parameters
• Add tests
The use case is as follows: 
If we have an OTel Kotlin instance, but we want to wrap it in an `OtelJavaOpenTelemetry` instance, we can use `OpenTelemetryInstance.compatWithOtelKotlin`. 
Once we are left with that instance, we should be able to set up a custom tracerBuilder like this: 
```
val schemaUrl = "https://opentelemetry.io/schemas/1.21.0"
val javaTracerWithSchemaUrl = tracerProvider.tracerBuilder("test-tracer")
.setInstrumentationVersion("2.0.0")
.setSchemaUrl(schemaUrl)
.build()
```
This would always leave us with a default tracer builder that results …
> Add OtelJavaTracerBuilderAdapter

- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaSpanExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/logging/LogExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExportTest.kt
- Add context passing test for Java spans in OtelJavaSpanExportTest
- Add context passing test for Kotlin spans in SpanExportTest
- Both tests verify that context is properly passed to span processors
> Add context passing tests for spans

- opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ObjectCreator.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/TracingIdCreator.kt
- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/CompatObjectCreator.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/TracingIdCreatorImpl.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/creator/SpanContextCreatorImplTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/creator/SpanCreatorImplTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/creator/TracingIdCreatorImplTest.kt
- opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/NoopObjectCreator.kt
- opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/NoopTracingIdCreator.kt
Alters the API for getting tracing IDs to ensure that the API is defined in the API module, not just the compat module.
> Alter API for getting tracing ids

- .github/workflows/gradle.yml
- build.gradle.kts
- buildSrc/src/main/kotlin/io/embrace/otel/BuildPlugin.kt
- buildSrc/src/main/kotlin/io/embrace/otel/KoverConfig.kt
- gradle/libs.versions.toml
Sets up code coverage to run automatically on CI and upload to codecov. This can be run locally with `./gradlew koverHtmlReport`.
This _should_ start working on subsequent PRs once this PR is merged.
> Setup code coverage

- build.gradle.kts
- buildSrc/src/main/kotlin/io/embrace/otel/BuildPlugin.kt
- buildSrc/src/main/kotlin/io/embrace/otel/KoverConfig.kt
- examples/android-app-java-api/gradle.properties
- examples/android-app-kotlin-api/gradle.properties
- examples/example-shared/gradle.properties
- examples/gradle.properties
- examples/jvm-app-java-api/gradle.properties
- examples/jvm-app-kotlin-api/gradle.properties
- examples/telescope-app/gradle.properties
- opentelemetry-java-typealiases/gradle.properties
- opentelemetry-kotlin-api-ext/build.gradle.kts
- opentelemetry-kotlin-api/build.gradle.kts
- opentelemetry-kotlin-compat/build.gradle.kts
- opentelemetry-kotlin-implementation/build.gradle.kts
- opentelemetry-kotlin-noop/build.gradle.kts
- opentelemetry-kotlin-testing/gradle.properties
Alters the setup of codecov so that adding a property to the gradle.properties of a module can disable it if needed. The `opentelemetry-kotlin-testing` and various other unwanted modules were reporting code coverage data, when we don't really mind about them given they're not production code.
> Tweak codecov setup

- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/ContextKeyExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/OtelJavaSpanContextExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/OtelJavaSpanKindExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/OtelJavaStatusCodeExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/SpanContextExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/SpanKindExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/StatusCodeExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/StatusDataExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/TraceFlagsExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/TraceStateExtTest.kt
Adds unit tests for some of the functions that convert between OTel Java and Kotlin.
> Add unit tests for conversion functions

- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/framework/OtelKotlinHarness.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/framework/TestHarnessConfig.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/logging/LogExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/logging/OtelJavaLogExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/OtelJavaSpanExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/resources/log_limits.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_attrs.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_edge_case_attributes.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_events.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_limits.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_minimal.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_multiple_operations.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_props.json
Adds integration tests that confirm limits are respected when exporting spans/logs. As part of this I refactored the test harness so that it's easier to override the default config in test cases.
> Add limit tests for spans/logs

- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/logging/OtelJavaLogRecordBuilderAdapter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/logging/OtelJavaLogRecordBuilderAdapterTest.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/FakeLogger.kt
Supports timestamps added with an `Instant` type. Some methods on this type is only available in Android API >=26 so I've surrounded this with a try-catch to avoid throwing, given we don't have access to Android API annotations in this module.
> Support timestamp supplied via instant

- opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/StatusCode.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/data/StatusData.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/Span.kt
- opentelemetry-kotlin-compat/build.gradle.kts
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/StatusCodeExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadWriteSpanAdapter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/java/FakeOtelJavaReadWriteSpan.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/StatusCodeExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadWriteSpanAdapterTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_custom_processor.json
- opentelemetry-kotlin-testing/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/testing/common/TestSpanProcessor.kt
Make the adapter call into the wrapped method to do updating and add tests to verify this in the `SpanProcessor` and `SpanExporter` layers where these objects are created. Previously, they were no-ops so updates were discarded.
Also, make the enum names consistent with Java because why not.
> Ensure ReadWriteSpan adapter updates the wrapped span

- opentelemetry-kotlin-implementation/build.gradle.kts
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/FakeLogRecordProcessor.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/FakeSpanProcessor.kt
Adds fake processors for spans/logs and ensures the implementation module can access them.
> Add fake processors for span/log

- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/init/LogLimitsConfigImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/init/SpanLimitsConfigImpl.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/init/LoggerProviderConfigImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/init/TracerProviderConfigImplTest.kt
Tweaks the default limits for spans/logs to match otel-java.
> Tweak limits for default spans/logs

- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/CompositeSpanProcessor.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/CompositeSpanProcessorTest.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/FakeReadWriteSpan.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/FakeSpanProcessor.kt
Implements a composite `SpanProcessor` that will be used to join processors supplied by the end-user together.
> Implement composite span processor

- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/OtelJavaSpanProcessorAdapterTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadWriteSpanAdapterTest.kt
Add to the `Span` interface that notion of the span's context at creation time. This is so it could be used in the API to create a span with this given span as a parent.
We can probably use a the root context as a basis but this is probably more complete.
> Add tests for SpanProcessor adapter

- buildSrc/src/main/kotlin/io/embrace/otel/KotlinConfig.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanImpl.kt
- opentelemetry-kotlin-primitives/api/opentelemetry-kotlin-primitives.api
- opentelemetry-kotlin-primitives/src/appleMain/kotlin/io/embrace/opentelemetry/kotlin/Sync.apple.kt
- opentelemetry-kotlin-primitives/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/Sync.kt
- opentelemetry-kotlin-primitives/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/Sync.jvm.kt
Implements a locking model for spans. The rules for this approach would be:
1. The span needs to be recording for any operation to take place
2. Any write operations must take place behind a lock
3. Read operations do not need to take place behind a lock, but must copy the collection/object if it's not immutable
The main consideration I had is whether _everything_ on the `Span` interface need to be behind the same lock? My default answer is yes, we could segment the locking if performance shows this is necessary later on.
The implementation of `doubleCheckedLockSync` also uses `synchronized` for the JVM. I wonder if `ReadWriteLock` would be a better fit, as that would allow multiple concurrent reads if no writes were happening.
> Span locking model

- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/CreatedSpan.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadWriteSpanImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadableSpanImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanRecord.kt
Makes the `SpanRecord` the single source of truth, and creates several views onto that truth in the form of read-only/write implementations that will be used in the processor/export cycle.
> Improve span model

- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/error/NoopSdkErrorHandler.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerProviderImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerProviderImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanRecord.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerProviderImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerProviderImplTest.kt
Passes through some pre-requisite objects for span processing to `SpanRecord`, such as the `Clock` and `SpanProcessor` implementations.
> Pass through pre-requisites for span processing

- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanRecord.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanAttributesTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanEndTest.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/clock/FakeClock.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/FakeSpanProcessor.kt
Adds initial support for the `onEnd` callback in span processing.
Added unit test coverage.
> Support onEnd for span processor

- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/ContextImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/ContextKeyImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ContextCreatorImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerProviderImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanRecord.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/context/ContextImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanAttributesTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanEndTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerProviderImplTest.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/FakeContextCreator.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/FakeObjectCreator.kt
Adds support for calling `onStart` for `SpanProcessor` when a span ends. 
> Add support for onStart call for span processors

- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanRecord.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanEndTest.kt
Refactors the management of the ending of spans in `SpanRecord` so that it's capable of ignoring calls to `end()` from within a `SpanProcessor`.
> Alter end state management in span record

- opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/model/ReadableSpanConversionTest.kt
- opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/model/ReadableSpanExt.kt
- opentelemetry-kotlin-implementation/src/jvmTest/resources/span_minimal.json
Improves the function that converts `ReadableSpan` into `SerializableSpanData` in the integration tests. This adds a bit more coverage when using the integration test frameworks as we have implemented more functionality that can be tested.
> Improve span conversion function

- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/CreatedSpan.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadWriteSpanImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadableSpanImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanModel.kt
Renames `SpanRecord` to `SpanModel`.
> Rename span record

- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/SpanContextCreator.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/HexUtils.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/TraceFlagsCreatorImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/HexUtils.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ObjectCreatorImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/SpanContextCreatorImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/TraceFlagsCreatorImpl.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/creator/SpanContextCreatorImplTest.kt
- Implement SpanContextCreator with OpenTelemetry-compliant trace/span ID validation
- Create shared HexUtils for hex validation
- Should we preserve the original invalid IDs instead of replacing with zeros? Current approach follows Java OpenTelemetry behavior
- HexUtils is duplicated in both modules to avoid cross-module dependencies - is this the preferred approach?
> Implement SpanContext Creator

- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ObjectCreatorImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/SpanCreatorImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/TraceFlagsCreatorImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanModel.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/creator/SpanCreatorImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/creator/TraceFlagsCreatorImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerSpanContextTest.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/FakeTracingIdCreator.kt
Supports populating the spanContext/parent properties on `SpanModel` with actual values.
> SpanModel span context

- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceCompat.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/CompatObjectCreator.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/init/TracerProviderConfigImpl.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/framework/OtelKotlinHarness.kt
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_attrs.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_custom_processor.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_edge_case_attributes.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_events.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_limits.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_links.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_minimal.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_multiple_operations.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_props.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_resource.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_schema_url.json
- opentelemetry-kotlin-compat/src/jvmTest/resources/span_tracer_builder.json
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ObjectCreatorImpl.kt
- opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/IntegrationTestHarness.kt
- opentelemetry-kotlin-implementation/src/jvmTest/resources/span_ancestry.json
- opentelemetry-kotlin-implementation/src/jvmTest/resources/span_attrs.json
- opentelemetry-kotlin-implementation/src/jvmTest/resources/span_basic_props.json
- opentelemetry-kotlin-implementation/src/jvmTest/resources/span_event.json
- opentelemetry-kotlin-implementation/src/jvmTest/resources/span_links.json
- opentelemetry-kotlin-implementation/src/jvmTest/resources/span_minimal.json
- opentelemetry-kotlin-integration-test/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/framework/serialization/conversion/SerializableLinkData.kt
- opentelemetry-kotlin-integration-test/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/framework/serialization/conversion/SerializableLogRecordData.kt
- opentelemetry-kotlin-integration-test/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/framework/serialization/conversion/SerializableSpanContext.kt
- opentelemetry-kotlin-integration-test/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/framework/serialization/conversion/SerializableSpanData.kt
Updates the integration tests to use consistent IDs for tracing by supplying a seed to the underlying random number generators for both the implementation + compat modules. This is a trade-off - on balance I think it's better to assert that the traceId/spanId matches an expected output in the JSON than it is to assert the compat module is using a specific implementation of `IdGenerator`.
> Use consistent trace IDs in integration tests

- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/LogRecordModel.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/logging/LogAttributesTest.kt
Supports population of attributes on the `LogRecordModel`.
> Support attributes on LogRecordModel

- opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/ReadableLogRecord.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/ReadWriteLogRecordAdapter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/logging/OtelJavaLogRecordBuilderAdapterTest.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/LogRecordModel.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/logging/LogContextTest.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/FakeLogger.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/FakeReadWriteLogRecord.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/FakeReadableLogRecord.kt
Implements Context propagation for the `LogModel` class. Reading the spec again, only the `SpanContext` needs to be part of the log record so I updated the inheritance hierarchy appropriately.
> Implement context for log model

- opentelemetry-kotlin-implementation/api/opentelemetry-kotlin-implementation.api
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ObjectCreatorExt.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/context/SpanStorageTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/creator/SpanCreatorImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/logging/LogContextTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerProviderImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerSpanContextTest.kt
Similar to how the default ObjectCreator is exposed for the compat module, do the same for the SDK module
> Expose ObjectCreator implementation for the SDK module

- opentelemetry-kotlin-implementation-java-compat/api/opentelemetry-kotlin-implementation-java-compat.api
- opentelemetry-kotlin-implementation-java-compat/build.gradle.kts
- opentelemetry-kotlin-implementation-java-compat/gradle.properties
- opentelemetry-kotlin-implementation-java-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryJavaExt.kt
- opentelemetry-kotlin-implementation-java-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OtelJavaOpenTelemetrySdk.kt
- settings.gradle.kts
Creates an extra module that will be used for Kotlin -> Java compatibility between the implementation layer and the OTel Java API.
> Setup extra compat module

- opentelemetry-kotlin-implementation/src/appleMain/kotlin/io/embrace/opentelemetry/kotlin/clock/ClockImpl.apple.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/clock/ClockImpl.kt
- opentelemetry-kotlin-implementation/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/clock/ClockImpl.jvm.kt
- opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/clock/ClockImplJvmTest.kt
- Java: Implemented using `System.currentTimeMillis() * 1_000_000L`
- apple: Implemented using `(NSDate().timeIntervalSince1970 * 1_000_000_000.0).toLong()`
> Use kotlinx.datetime for implementing Clock.now()

- opentelemetry-kotlin-api-ext/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryExt.kt
- opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/Clock.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/InstrumentationScopeInfo.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/attributes/AttributeContainer.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/init/LoggerProviderConfigDsl.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/init/ResourceConfigDsl.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/init/TracerProviderConfigDsl.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/data/EventData.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/data/LinkData.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/data/SpanData.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/data/SpanSchema.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/data/StatusData.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadableSpan.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/init/CompatLoggerProviderConfig.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/init/CompatTracerProviderConfig.kt
- opentelemetry-kotlin-implementation/build.gradle.kts
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/init/ResourceConfigImpl.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/init/LoggerProviderConfigImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/init/TracerProviderConfigImplTest.kt
Makes some tweaks to the API based on self-review of all the entire surface. This includes:
- Some missing documentation
- Making `Clock` a `fun` interface to enable SAM conversions if an end-users wishes to do so
- Adds an overload to specifying the resource that allows creating one from just a map
> API surface tweaks

- examples/example-common/src/commonMain/kotlin/io/embrace/opentelemetry/example/kotlin/OtelKotlinExample.kt
- opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetry.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/logging/LogExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanExportTest.kt
- opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/logging/LogProcessorNaughtyExportTest.kt
- opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/logging/LogProcessorOnEmitTest.kt
- opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/logging/LoggerExportTest.kt
- opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/tracing/TracerExportTest.kt
- opentelemetry-kotlin-integration-test/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/framework/OtelKotlinTestRule.kt
- opentelemetry-kotlin-model/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryImpl.kt
- opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/NoopOpenTelemetry.kt
- opentelemetry-kotlin-noop/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/NoopTests.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/FakeOpenTelemetry.kt
Builds on #352 by making `OpenTelemetry` supply the factories for creating objects such as `SpanContext/TraceState`.
> Make OpenTelemetry interface supply factories

- examples/telescope-app/app/src/main/java/io/embrace/opentelemetry/kotlin/telescope/telemetry/AppTracerProvider.kt
- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryCompatExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceCompat.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OtelJavaOpenTelemetryExt.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/framework/OtelKotlinHarness.kt
- opentelemetry-kotlin-testing/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/testing/junit4/OpenTelemetryRule.kt
- opentelemetry-kotlin-testing/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/testing/junit5/OpenTelemetryExtension.kt
Reduces the number of functions on `OpenTelemetryInstance` by replacing APIs that are simply converting between the Java/Kotlin `OpenTelemetry` interface in the compat module with extension functions instead.
> Reduce number of functions on OpenTelemetryInstance

- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordExporterAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordExporterExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordProcessorAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordProcessorExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/ReadWriteLogRecordAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/OtelJavaSpanExporterExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanExporterAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanExporterExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanProcessorAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanProcessorExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadWriteSpanAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/ReadableSpanAdapter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/java/FakeOtelJavaLogRecordProcessor.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/java/FakeOtelJavaSpanProcessor.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordExporterAdapterTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordExporterExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordProcessorExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanExporterAdapterTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanExporterExtTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanProcessorExtTest.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/FakeReadWriteLogRecord.kt
Implements conversion functions on our public API that convert an opentelemetry-java exporter/processor to the Kotlin API. This will be essential for using the SDK until we implement our own OTLP exporters.
> Add conversion functions for existing exporters/processors

- examples/example-common/src/commonMain/kotlin/io/embrace/opentelemetry/example/kotlin/OtelKotlinExample.kt
- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryCompatEntrypoint.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryCompatExt.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OtelJavaOpenTelemetryExt.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetrySdkTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/framework/OtelKotlinHarness.kt
- opentelemetry-kotlin-implementation/api/opentelemetry-kotlin-implementation.api
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryImplEntrypoint.kt
- opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/IntegrationTestHarness.kt
- opentelemetry-kotlin-noop/api/opentelemetry-kotlin-noop.api
- opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/NoopOpenTelemetryEntrypoint.kt
- opentelemetry-kotlin-noop/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/NoopTests.kt
Renames the API entrypoints as suggested in #355 so that they use consistent naming of `create<Token>OpenTelemetry()`.
> Rename api entrypoints

- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/factory/CompatSdkFactoryExt.kt
Reduces the visibility of `createCompatSdkFactory` which is an internal implementation detail.
> Reduce visibility of createCompatSdkFactory

- opentelemetry-kotlin-implementation/build.gradle.kts
Fixes an issue with the build dependency where the `integration-test` module was inadvertantly added to `commonMain` instead of `commonTest`. Because this module doesn't publish to Maven Central this results in 0.5.0 failing to resolve the dependency. The ultimate fix will be to avoid using 0.5.0 and to ship a new release that doesn't request this dependency.
> Fixes build dependency issue

- opentelemetry-kotlin-exporters/README.md
- opentelemetry-kotlin-exporters/build.gradle.kts
- settings.gradle.kts
Adds the skeleton of an exporter module & a gradle task that download protobuf definitions from the correct OpenTelemetry repo.
> Add exporter module

- opentelemetry-kotlin-exporters/src/main/kotlin/io/embrace/opentelemetry/kotlin/export/ExportDefaults.kt
- opentelemetry-kotlin-exporters/src/main/kotlin/io/embrace/opentelemetry/kotlin/export/TelemetryExporter.kt
- opentelemetry-kotlin-exporters/src/main/kotlin/io/embrace/opentelemetry/kotlin/logging/export/OtlpHttpLogRecordExporterApi.kt
- opentelemetry-kotlin-exporters/src/main/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/OtlpHttpSpanExporter.kt
- opentelemetry-kotlin-exporters/src/main/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/OtlpHttpSpanExporterApi.kt
- opentelemetry-kotlin-exporters/src/test/kotlin/io/embrace/opentelemetry/kotlin/logging/export/OtlpHttpLogRecordExporterTest.kt
- opentelemetry-kotlin-exporters/src/test/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/OtlpHttpSpanExporterTest.kt
Adds exporters for log records & spans that are capable of exporting telemetry over [OTLP via HTTP](https://opentelemetry.io/docs/specs/otlp/#otlphttp), with binary protobuf encoding. The exporters use coroutines and exponential backoff to retry if an initial attempt fails.
> Add Otlp HTTP exporters

- examples/example-common/src/jvmMain/kotlin/io/embrace/opentelemetry/example/kotlin/ExportConfig.jvm.kt
- opentelemetry-kotlin-exporters/api/opentelemetry-kotlin-exporters.api
- opentelemetry-kotlin-exporters/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/CompositeLogRecordProcessor.kt
- opentelemetry-kotlin-exporters/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/LogRecordExporterApi.kt
- opentelemetry-kotlin-exporters/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/OtlpHttpLogRecordExporterApi.kt
- opentelemetry-kotlin-exporters/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/SimpleLogRecordProcessor.kt
- opentelemetry-kotlin-exporters/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/CompositeSpanProcessor.kt
- opentelemetry-kotlin-exporters/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/OtlpHttpSpanExporterApi.kt
- opentelemetry-kotlin-exporters/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SimpleSpanProcessor.kt
- opentelemetry-kotlin-exporters/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/SpanExporterApi.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryImplEntrypoint.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerProviderImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerProviderImpl.kt
Alters the API for creating exporters/processors to hide unnecessary implementation details.
> Alter exporter/processor API

- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/attributes/MutableAttributeContainerImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/init/ResourceConfigImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/resource/ResourceImpl.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/init/LoggerProviderConfigImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/init/TracerProviderConfigImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerProviderImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/resource/ResourceImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanEventTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanLinkTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerProviderImplTest.kt
Enforces the [default attribute limit](https://opentelemetry.io/docs/specs/otel/common/#attribute-limits) in a few places where it wasn't being applied, and adds tests for several scenarios where it is.
Added tests
> Enforce default attribute limit consistently

- opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/Logger.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/ReadWriteLogRecord.kt
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/ReadableLogRecord.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerAdapter.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/ReadWriteLogRecordAdapter.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/logging/LogExportTest.kt
- opentelemetry-kotlin-compat/src/jvmTest/resources/event.json
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerImpl.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/LogRecordModel.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/logging/LogProcessorOnEmitTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/logging/LoggerExportTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/resources/event.json
- opentelemetry-kotlin-implementation/src/commonTest/resources/log_emit_override.json
- opentelemetry-kotlin-integration-test/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/framework/serialization/SerializableLogRecordData.kt
- opentelemetry-kotlin-integration-test/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/framework/serialization/conversion/SerializableLogRecordData.kt
- opentelemetry-kotlin-integration-test/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/framework/serialization/SerializableLogRecordDataTest.kt
- opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/NoopLogger.kt
- opentelemetry-kotlin-noop/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/NoopTests.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/FakeLogger.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/FakeReadWriteLogRecord.kt
- opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/FakeReadableLogRecord.kt
Implements the Events API as per the OTel spec: https://opentelemetry.io/docs/specs/otel/logs/data-model/#events
> Add events api

- opentelemetry-kotlin-api-ext/api/opentelemetry-kotlin-api-ext.api
- opentelemetry-kotlin-api-ext/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/ContextApiExt.kt
- opentelemetry-kotlin-api-ext/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/context/ContextExtTest.kt
Adds an extension function for creating a new `Context` object. The extension syntax looks like this:
```
val newCtx = root.with(mapOf("key" to "value"))
```
Whereas the API that follows the explicit OTel API looks like this:
```
val key = root.createKey<String>("key")
val newCtx = root.set(key, "value")
```
> Add extension for creating new context

- examples/example-common/src/commonMain/kotlin/io/embrace/opentelemetry/example/kotlin/OtelKotlinExample.kt
- opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api
- opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/init/OpenTelemetryConfigDsl.kt
- opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryCompatEntrypoint.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/init/CompatLoggerProviderConfig.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/init/CompatOpenTelemetryConfig.kt
- opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/init/CompatTracerProviderConfig.kt
- opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/framework/OtelKotlinHarness.kt
- opentelemetry-kotlin-implementation/api/opentelemetry-kotlin-implementation.api
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryImplEntrypoint.kt
- opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/init/OpenTelemetryConfigImpl.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/init/OpenTelemetryConfigImplTest.kt
- opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/IntegrationTestHarness.kt
- opentelemetry-kotlin-integration-test/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/framework/OtelKotlinTestRule.kt
Makes a tweak to the syntax of creating an `OpenTelemetry` instance by creating `OpenTelemetryConfigDsl` that contains all the other config values. This should allow for greater backwards compatibility in future as using only one parameter means it's easy to add extra values to the config in future, rather than needing to add a new parameter.
> Tweak entrypoint syntax
