embrace-io/opentelemetry-kotlin

compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/context/ContextAdapter.kt, opentelemetry-kotlin-api/api/android/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/api/jvm/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/Context.kt
Alters the Context API by using operator overloading for better syntax.
=> Alter context api with operator

examples/example-shared/src/main/java/io/embrace/opentelemetry/example/kotlin/OtelKotlinExample.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanRelationshipContainer.kt
Improves our example app by adding more uses of our API so that the full surface is explored.
=> Improve example app

compat-kotlin-to-official/api/jvm/compat-kotlin-to-official.api, compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanAdapter.kt, compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanContextAdapter.kt, compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TraceFlagsAdapter.kt, opentelemetry-kotlin-api-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/NoopTraceFlags.kt, opentelemetry-kotlin-api/api/android/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/api/jvm/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TraceFlags.kt
Makes a couple of API tweaks that will allow us to use the Kotlin API in the Embrace Android SDK.
=> Api tweaks to support android sdk

compat-kotlin-to-official/api/jvm/compat-kotlin-to-official.api, compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanAdapter.kt, compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TracerAdapter.kt, opentelemetry-java-typealiases/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/aliases/Aliases.kt
Add additional typealiases that will be used when interacting with symbols from opentelemetry-java
=> Add additional typealiases for OTel java

compat-kotlin-to-official/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/OpenTelemetrySdk.kt, examples/example-shared/src/main/java/io/embrace/opentelemetry/example/kotlin/OtelKotlinExample.kt, opentelemetry-kotlin-api/api/android/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/api/jvm/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetry.kt, opentelemetry-kotlin-implementation/api/android/opentelemetry-kotlin-implementation.api, opentelemetry-kotlin-implementation/api/jvm/opentelemetry-kotlin-implementation.api, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/clock/ClockImpl.kt, opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/NoopOpenTelemetry.kt
Adds a property for exposing the `Clock` instance.
=> Add property for exposing clock on interface

opentelemetry-kotlin-api/api/android/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/api/jvm/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/InstrumentationScopeInfo.kt
Adds an API for accessing the instrumentation scope.
=> Add instrumentation scope api

opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracingFactory.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanContext.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/TraceState.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanContextAdapter.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanContextOtelJavaConverter.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TraceStateAdapter.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/java/FakeOtelJavaClock.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/java/FakeOtelJavaLogRecordData.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/java/FakeOtelJavaLogRecordExporter.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/java/FakeOtelJavaSpanData.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/java/FakeOtelJavaSpanExporter.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeContext.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeContextKey.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeInstrumentationScopeInfo.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeReadableLink.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeReadableLogRecord.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeReadableSpan.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeReadableSpanEvent.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeResource.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeSpanContext.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeTraceFlags.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeTraceState.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/framework/OtelKotlinHarness.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/framework/serialization/SerializableLogRecordDataTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/framework/serialization/SerializableSpanDataTest.kt
Adds fake implementations that will be used by the span/log exporters.
=> Add fake implementations

opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryInstanceK2J.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/OpenTelemetrySdk.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/init/LoggerProviderConfigImpl.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/init/OtelJavaClockWrapper.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/init/SpanLimitsConfigImpl.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/init/TracerProviderConfigImpl.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeClock.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/init/SpanLimitsConfigImplTest.kt
Begins implementing the compat layer of the Kotlin DSL. Span/Log processors will be implemented in a future PR.
Added unit tests where possible - span/log providers will be covered by integration tests which need adapting in a future PR.
=> Begin implementing kotlin DSL

opentelemetry-kotlin-implementation/api/opentelemetry-kotlin-implementation.api, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/ReadWriteLogRecordImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/ReadWriteSpanImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/ReadableSpanImpl.kt
Adds initial implementations for some model classes that are required by the span/log processors.
=> Add model class implementations

CHANGELOG.md, gradle.properties
=> Add changelog entry

.github/workflows/publish-snapshot.yml, README.md
Also added instructions to use said snapshots on an app.
=> Add publish-snapshot.yml to publish snapshots manually, and on a daily basis 

opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/Clock.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/InstrumentationScopeInfo.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/export/OperationResultCode.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/export/TelemetryCloseable.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/init/ConfigDsl.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/SeverityNumber.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/StatusCode.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TraceStateMutator.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracingDsl.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracingFactory.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanContextOrigin.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanKind.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/TraceFlags.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/OperationResultCode.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/bridge/InstrumentationScopeInfoExt.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaSpanKindConversion.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaStatusCodeConversion.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/ClockAdapter.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/init/OtelJavaClockWrapper.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/logging/SeverityNumberConversion.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanContextOtelJavaConverter.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanKindConversion.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/StatusCodeConversion.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/TraceFlagsAdapter.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeClock.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeInstrumentationScopeInfo.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/fakes/otel/kotlin/FakeTraceFlags.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/InstrumentationScopeInfoImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/clock/ClockImpl.kt, opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/NoopClock.kt
Adds the `ExperimentalApi` annotation to all symbols on the public interface.
=> Add ExperimentalApi annotation

opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExportTest.kt, opentelemetry-kotlin-compat/src/jvmTest/resources/span_edge_case_attributes.json, opentelemetry-kotlin-compat/src/jvmTest/resources/span_multiple_operations.json
• Add trace state propagation and validation test
• Add edge case testing for attributes (empty strings, lists, whitespace)
• Add test for multiple spans, events, and links
• Add trace/span ID validation
=> Add additional testing for span exporting

CONTRIBUTING.md
Adds guidelines for contributing to the project.
=> Add guidelines for contributing

opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/logging/LogExportTest.kt
Added a test that verifies that when context is passed to a log, it's sent correctly to the log processors added to its logger.
=> Test passing a context to a log

opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ObjectCreator.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/TraceFlagsCreator.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/TraceStateCreator.kt, opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/CompatObjectCreator.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/CompatObjectCreatorExt.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/TraceFlagsCreatorImpl.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/TraceStateCreatorImpl.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/creator/SpanContextCreatorImplTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/creator/TraceFlagsCreatorImplTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/creator/TraceStateCreatorImplTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExtTest.kt, opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/NoopObjectCreator.kt, opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/NoopTraceFlagsCreator.kt, opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/NoopTraceStateCreator.kt
Builds on #232 by adding an API for creating `TraceFlags` and `TraceState` objects.
=> Add trace flag/state creator API

examples/example-shared/src/main/java/io/embrace/opentelemetry/example/kotlin/OtelKotlinExample.kt, opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ContextCreator.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ObjectCreator.kt, opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/CompatObjectCreator.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ContextCreatorExt.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ContextCreatorImpl.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/creator/ContextCreatorImplTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/context/ContextAdapterTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExportTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExtTest.kt, opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/NoopContext.kt, opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/context/NoopContextKey.kt, opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/NoopContextCreator.kt, opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/NoopObjectCreator.kt
Builds on #233 by adding an API for retrieving `Context` objects.
=> Add context creator API

opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/ObjectCreator.kt, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/SpanCreator.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/CompatObjectCreator.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/creator/SpanCreatorImpl.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/SpanExtTest.kt, opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/NoopObjectCreator.kt, opentelemetry-kotlin-noop/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/creator/NoopSpanCreator.kt
Builds on #234 by adding an API for creating `Span` objects.
=> Span creator API

opentelemetry-kotlin-compat/api/opentelemetry-kotlin-compat.api, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaSpanKindConversion.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/j2k/tracing/OtelJavaStatusCodeConversion.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/StatusCodeConversion.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/k2j/tracing/StatusDataConversion.kt
Reduces the visibility to internal of some functions that don't need to be publicly exposed.
=> Reduce visibility of unneeded functions

README.md
Adds a codecov badge to our changelog.
=> Add codecov badge to changelog

codecov.yml
- Adds codecov.yml configuration file to define coverage requirements
- Sets project coverage to use `adjust_base` behavior (adjusts base coverage when code is removed)
- Requires 50% minimum coverage for new code in pull requests
- This PR also serves as a test to see if adding the codecov.yml file makes Codecov comment on PRs.
=> Add codecov.yml configuration

opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanModel.kt, opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanDataTest.kt, opentelemetry-kotlin-model/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanDataImpl.kt
Implements `toSpanData` on `SpanModel`
Added unit tests
=> Implement toSpanData on SpanModel

opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/LogRecordModel.kt, opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/logging/LogSimplePropertiesTest.kt
Implements the simple properties on `LogModel`.
=> Implement simple log properties

opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/logging/LoggerExportTest.kt, opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/tracing/SpanProcessNaughtyOnEndTest.kt, opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/tracing/SpanProcessOnEndReadTest.kt, opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/tracing/SpanProcessOnStartOverrideTest.kt, opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/tracing/TracerExportTest.kt, opentelemetry-kotlin-implementation/src/jvmTest/resources/log_attrs.json, opentelemetry-kotlin-implementation/src/jvmTest/resources/log_basic_props.json, opentelemetry-kotlin-implementation/src/jvmTest/resources/log_minimal.json, opentelemetry-kotlin-implementation/src/jvmTest/resources/log_resource_scope.json, opentelemetry-kotlin-implementation/src/jvmTest/resources/log_root_context.json, opentelemetry-kotlin-implementation/src/jvmTest/resources/log_span_context.json, opentelemetry-kotlin-integration-test/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/framework/OtelKotlinTestRule.kt
Adds integration tests for the logging pipeline.
=> Add integration test cases for logger

opentelemetry-kotlin-api/api/opentelemetry-kotlin-api.api, opentelemetry-kotlin-api/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/ReadWriteLogRecord.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/logging/LogExportTest.kt, opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/logging/LogProcessorNaughtyExportTest.kt, opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/logging/LogProcessorOnEmitTest.kt, opentelemetry-kotlin-implementation/src/jvmTest/resources/log_emit_override.json, opentelemetry-kotlin-implementation/src/jvmTest/resources/log_naughty_export.json
Adds some additional tests that verify the behavior of the log exporting.
=> Add integration tests for logger

RELEASING.md
Adds instructions for how to ship a release.
=> Add instructions for releasing

custom-detekt-rules/gradle.properties, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryCompatEntrypoint.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/ReadWriteLogRecordAdapter.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/OtelJavaSpanBuilderAdapter.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerAdapter.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/OtelJavaOpenTelemetryExtTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/factory/ContextFactoryImplTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/logging/export/ReadableLogRecordExtTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/resource/ResourceAdapterTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/ext/SpanDataExtTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/TraceStateAdapterTest.kt, opentelemetry-kotlin-implementation/src/appleMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryAppleEntrypoint.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryImplEntrypoint.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/LogRecordModel.kt, opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/init/LoggerProviderConfigImplTest.kt, opentelemetry-kotlin-implementation/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/init/TracerProviderConfigImplTest.kt, opentelemetry-kotlin-implementation/src/commonTest/resources/span_complex_java_api.json, opentelemetry-kotlin-implementation/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/integration/test/OtelJavaApiExportTest.kt, opentelemetry-kotlin-noop/src/commonTest/kotlin/io/embrace/opentelemetry/kotlin/NoopTests.kt, opentelemetry-kotlin-test-fakes/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/FakeSpan.kt
Increases test coverage as reported by Kover by adding misc test cases as required.
=> Begin increasing test coverage

opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/OtelJavaOpenTelemetryExt.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/init/CompatTracerProviderConfig.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerAdapter.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerProviderAdapter.kt, opentelemetry-kotlin-compat/src/jvmMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanAdapter.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/context/ContextRetrievalTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanExportTest.kt, opentelemetry-kotlin-compat/src/jvmTest/kotlin/io/embrace/opentelemetry/kotlin/tracing/SpanExtTest.kt, opentelemetry-kotlin-implementation/src/appleMain/kotlin/io/embrace/opentelemetry/kotlin/OpenTelemetryAppleEntrypoint.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/attributes/MutableAttributeContainerImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/factory/ContextFactoryImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/factory/SdkFactoryImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/factory/SpanFactoryImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/factory/TraceFlagsFactoryImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/factory/TraceStateFactoryImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerProviderImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/provider/ApiProviderImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/model/SpanModel.kt
Makes some performance optimizations after reviewing the microbenchmark results.
=> Optimize performance

opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/factory/TracingIdFactoryImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/LoggerImpl.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/model/LogRecordModel.kt, opentelemetry-kotlin-implementation/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/TracerImpl.kt, opentelemetry-kotlin-model/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/NonRecordingSpan.kt
Makes further performance optimizations on the log/span pipelines.
=> Further performance optimizations

examples/android-app/build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat
=> Bump gradle to 9.1.0

opentelemetry-kotlin-exporters/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/logging/export/CompositeLogRecordProcessor.kt, opentelemetry-kotlin-exporters/src/commonMain/kotlin/io/embrace/opentelemetry/kotlin/tracing/export/CompositeSpanProcessor.kt
Adds a lock to the composite processor implementations to match the simple processor implementations.
=> Add lock for processor

README.md
Added instructions for Regular and Compatibility modes in the README.
=> Enhance README with setup instructions for SDK
